### ISSUE TITLE
how to convert .cool、.h5、.hic、.mcool file to .matrix.txt file ?

### ISSUE THREAD

**Issue by shaoxiong2588** [dhkron/PSYCHIC#16]
how to convert .cool、.h5、.hic、.mcool file to .matrix.txt file ?

**Comment by yuvlyg** [comment]
it seems like `cooler` can dump .cool files to .txt matrices, but I haven't tried myself
https://cooler.readthedocs.io/en/stable/cli.html#cooler-dump
please re-open the issue if you're still having problems
