### ISSUE TITLE
Error occured in stage DixonDomainHMMCalling

### ISSUE THREAD

**Issue by LHX19962021** [dhkron/PSYCHIC#17]
python /disk/***/software/PSYCHIC/htad-chain.py \
> /disk/***/software/PSYCHIC/examples/himr90.chr20.conf
Not fixing matrix
Running stage DixonDI
sh: 1: pushd: not found
sh: 1: Syntax error: Bad fd number
Stage DixonDI done in 0.001698 seconds
Running stage DixonDomainHMMCalling
sh: 1: pushd: not found
sh: 1: popd: not found
Stage DixonDomainHMMCalling done in 6.944019 seconds
Error occured in stage DixonDomainHMMCalling

[?1h=
                                                           < M A T L A B (R) >
                                                 Copyright 1984-2019 The MathWorks, Inc.
                                                 R2019b (9.7.0.1190202) 64-bit (glnxa64)
                                                             August 21, 2019

 
To get started, type doc.
For product information, visit www.mathworks.com.
 
Loading modules... Done! 0.0013 seconds
Initializing & loading... AAABBBCCCAAA
ans =

    'Error using importdata (line 139)
     Unable to open file.
     
     Error in HMM_calls (line 13)
     data = importdata(filename);%Was just 'load', cause problem with chrX'

[?1l>

This matlab error occurs all the time, how should I solve it?

**Comment by yuvlyg** [comment]
it seems like your system doesn't have `pushd` and `popd`
please use a terminal that does support them, like bash or zsh 
please re-open if still facing issues
