### ISSUE TITLE
Basic Question

### ISSUE THREAD

**Issue by NicMAlexandre** [dhkron/PSYCHIC#18]
Hello,

I ran nf-core/hic on my data, which uses HiC-Pro and have my output matrices in the contact_maps/cool directory of the output. I'm wondering if this cool file e.g. OMNIC_REP1.40000_balanced.cool is sufficient as input or do I need more preprocessing.

**Comment by yuvlyg** [comment]
Hi,
Files in .cool format aren't supported, the program expects raw Hi-C matrices in text format (csv or tab-separated).

it seems like cooler can dump .cool files to .txt matrices, but I haven't tried myself
[cooler-dump](https://cooler.readthedocs.io/en/stable/cli.html#cooler-dump
)
please re-open the issue if it doesn't work for you
