### ISSUE TITLE
Error when run example

### ISSUE THREAD

**Issue by MinngLi** [dhkron/PSYCHIC#4]
Hi,

I got an error when I run the example which you provided. 

Not fixing matrix
Skipping stage DixonDI
Running stage DixonDomainHMMCalling
Stage DixonDomainHMMCalling done in 134.025175 seconds
Skipping stage DixonDomains1
Skipping stage DixonDomains2
Skipping stage FixMatrixFormat
Skipping stage domain_debug
Skipping stage GenerateProbModel
Skipping stage GenerateSupersum
Skipping stage FindTADsNewModel
Skipping stage FindHierarchies
Running stage ModelEstimate
Stage ModelEstimate done in 10.530208 seconds
Error occured in stage ModelEstimate

sh: line 1: 21845 Killed                  matlab -nodisplay -r "try HMM_calls ./PSYCHIC-master/examples/output1/mCO.chr12.DI ./PSYCHIC-master/examples/output1/mCO.chr12.HMM;catch E;fprintf('AAABBBCCCAAA');getReport(E),end;exit" >./PSYCHIC-master/examples/output1/mCO.chr12.mdump1 2> ./PSYCHIC-master/examples/output1/mCO.chr12.mdump1

Can you give me some help?

**Comment by dhkron** [comment]
Hello!

Can you please provide the output file `./PSYCHIC-master/examples/output1/mCO.chr12.mdump1`?
The detailed error should be there.
Also if you have any `*.mdump*` they might contain more detailed info.

Also, I see lots of steps were skipped.. is this 'vanilla' run, or you ran it several times?

**Comment by MinngLi** [comment]
Yes, I ran it several times.

Just now, I empty the output directory and run it again.

############################
For human example data:

Creating a Dixon-compatible matrix...
Done!
Running stage DixonDI
Stage DixonDI done in 0.746571 seconds
Running stage DixonDomainHMMCalling
Stage DixonDomainHMMCalling done in 147.740855 seconds
Running stage DixonDomains1
Stage DixonDomains1 done in 0.166019 seconds
Running stage DixonDomains2
Stage DixonDomains2 done in 0.069090 seconds
Running stage FixMatrixFormat
Stage FixMatrixFormat done in 0.571749 seconds
Skipping stage domain_debug
Running stage GenerateProbModel
Stage GenerateProbModel done in 11.518179 seconds
Running stage GenerateSupersum
Stage GenerateSupersum done in 14.867214 seconds
Running stage FindTADsNewModel
Stage FindTADsNewModel done in 55.678861 seconds
Running stage FindHierarchies
Stage FindHierarchies done in 8.262764 seconds
Running stage ModelEstimate
Stage ModelEstimate done in 7.231328 seconds
Error occured in stage ModelEstimate

sh: line 1: 30450 Killed                  matlab -nodisplay -r "try HMM_calls ./PSYCHIC-master/examples/output/hIMR90.chr20.DI ./PSYCHIC-master/examples/output/hIMR90.chr20.HMM;catch E;fprintf('AAABBBCCCAAA');getReport(E),end;exit" > ./PSYCHIC-master/examples/output/hIMR90.chr20.mdump1 2> ./PSYCHIC-master/examples/output/hIMR90.chr20.mdump1

####################################
mdump1 file:
------------------------------------------------------------------------
      Floating point exception detected at Mon Jan  8 17:06:34 2018
------------------------------------------------------------------------

Configuration:
  Crash Decoding     : Disabled
  Current Visual     : None
  Default Encoding   : UTF-8
  GNU C Library      : 2.12 stable
  MATLAB Architecture: glnxa64
  MATLAB Root        : /stor9000/apps/appsoftware/MATLAB/R2014a
  MATLAB Version     : 8.3.0.532 (R2014a)
  Operating System   : Linux 2.6.32-431.el6.x86_64 #1 SMP Sun Nov 10 22:19:54 EST 2013 x86_64
  Processor ID       : x86 Family 6 Model 79 Stepping 1, GenuineIntel
  Virtual Machine    : Java 1.7.0_11-b21 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
  Window System      : No active display

Fault Count: 1


Abnormal termination:
Floating point exception

Register State (from fault):
  RAX = 0000000000000012  RBX = 00002b7f0288dd60
  RCX = 0000000000000000  RDX = 0000000000000000
  RSP = 00002b7e9fff4ec0  RBP = 00002b7e9fff5180
  RSI = 00002b7e9fff4f90  RDI = 00002b7e9fff4f50

   R8 = 00002b7ea4f12430   R9 = 0000000000007727
  R10 = 0000000000000012  R11 = 00002b7e8522f672
  R12 = 00002b7f026e78c0  R13 = 0000000000000619
  R14 = 00002b7e9fff4ff0  R15 = 0000000000000001

  RIP = 00002b7eda79edb3  EFL = 0000000000010246

   CS = 0033   FS = 0000   GS = 0000

Stack Trace (from fault):
[  0] 0x00002b7eda79edb3 /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwmathelem.so+06208947
[  1] 0x00002b7eda79a388 /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwmathelem.so+06189960
[  2] 0x00002b7eda79b5ed /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwmathelem.so+06194669
[  3] 0x00002b7e8a377de3 /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwm_dispatcher.so+00417251
[  4] 0x00002b7e8a364874 /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwm_dispatcher.so+00338036 _ZN13Mfh_MATLAB_fn11dispatch_fhEiPP11mxArray_tagi
S2_+00000244
[  5] 0x00002b7e8b17fba3 /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+03754915
[  6] 0x00002b7e8b0a9101 /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02875649
[  7] 0x00002b7e8b0aa0ae /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02879662
[  8] 0x00002b7e8b0b8019 /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02936857
[  9] 0x00002b7e8b0b8183 /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02937219
[ 10] 0x00002b7e8b1ee172 /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+04206962
[ 11] 0x00002b7e8b023589 /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02327945
[ 12] 0x00002b7e8b026167 /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02339175
[ 13] 0x00002b7e8b02426f /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02331247
[ 14] 0x00002b7e8b024ec4 /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02334404
[ 15] 0x00002b7e8b08230b /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02716427
[ 16] 0x00002b7e8a3b5ad9 /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwm_dispatcher.so+00670425 _ZN8Mfh_file11dispatch_fhEiPP11mxArray_tagiS2_+00
000697
[ 17] 0x00002b7e8b06620e /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02601486
[ 18] 0x00002b7e8b0211d0 /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02318800
[ 19] 0x00002b7e8b0231ea /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02327018
[ 20] 0x00002b7e8b026167 /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02339175
[ 21] 0x00002b7e8b02426f /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02331247
[ 22] 0x00002b7e8b024ec4 /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02334404
[ 23] 0x00002b7e8b08230b /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02716427
[ 24] 0x00002b7e8a3b5ad9 /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwm_dispatcher.so+00670425 _ZN8Mfh_file11dispatch_fhEiPP11mxArray_tagiS2_+00
000697
[ 25] 0x00002b7e8b06620e /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02601486
[ 26] 0x00002b7e8b0211d0 /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02318800
[ 27] 0x00002b7e8b0231ea /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02327018
[ 28] 0x00002b7e8b026167 /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02339175
[ 29] 0x00002b7e8b02426f /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02331247
[ 30] 0x00002b7e8b024ec4 /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02334404
[ 31] 0x00002b7e8b08230b /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02716427
[ 32] 0x00002b7e8a3b5ad9 /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwm_dispatcher.so+00670425 _ZN8Mfh_file11dispatch_fhEiPP11mxArray_tagiS2_+00
000697
[ 33] 0x00002b7e8b06620e /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02601486
[ 34] 0x00002b7e8b0211d0 /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02318800
[ 35] 0x00002b7e8b0231ea /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02327018
[ 36] 0x00002b7e8b026167 /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02339175
[ 37] 0x00002b7e8b02426f /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02331247
[ 38] 0x00002b7e8b024ec4 /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02334404
[ 39] 0x00002b7e8b08230b /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02716427
[ 40] 0x00002b7e8a3b5c5f /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwm_dispatcher.so+00670815 _ZN8Mfh_file11dispatch_fhEiPP11mxArray_tagiS2_+00
001087
[ 41] 0x00002b7e8b055135 /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02531637
[ 42] 0x00002b7e8b01c0d9 /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02298073
[ 43] 0x00002b7e8b0199e1 /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02288097
[ 44] 0x00002b7e8b019bf1 /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02288625
[ 45] 0x00002b7e8b01b290 /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+02294416
[ 46] 0x00002b7e8afc0a75 /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwm_interpreter.so+01923701 _Z51inEvalCmdWithLocalReturnInDesiredWSAndPublis
hEventsPKcPibbP15inWorkSpace_tag+00000085
[ 47] 0x00002b7e892a2e68 /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwiqm.so+00650856 _ZNK3iqm18InternalEvalPlugin24inEvalCmdWithLocalReturnERKS
bIDsSt11char_traitsIDsESaIDsEEP15inWorkSpace_tag+00000120
[ 48] 0x00002b7e892a3328 /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwiqm.so+00652072 _ZN3iqm18InternalEvalPlugin7executeEP15inWorkSpace_tagRN5b
oost10shared_ptrIN14cmddistributor17IIPCompletedEventEEE+00000120
[ 49] 0x00002b7e8145d0c5 /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwmcr.so+00434373
[ 50] 0x00002b7e89295565 /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwiqm.so+00595301
[ 51] 0x00002b7e89283b05 /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwiqm.so+00523013
[ 52] 0x00002b7e89515ad9 /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwbridge.so+00121561 _Z10ioReadLinebP8_IO_FILERKN5boost8optionalIKP15inWorkS
pace_tagEEb+00000345
[ 53] 0x00002b7e89516081 /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwbridge.so+00123009
[ 54] 0x00002b7e8951ac2d /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwbridge.so+00142381
[ 55] 0x00002b7e8951afe9 /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwbridge.so+00143337
[ 56] 0x00002b7e8951b70b /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwbridge.so+00145163 _Z8mnParserv+00000587
[ 57] 0x00002b7e8146a92f /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwmcr.so+00489775 _ZN11mcrInstance30mnParser_on_interpreter_threadEv+0000003
1
[ 58] 0x00002b7e8144bb6d /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwmcr.so+00363373
[ 59] 0x00002b7e8144bbe9 /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwmcr.so+00363497
[ 60] 0x00002b7e80ce0e33 /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwservices.so+01646131 _ZN10eventqueue18UserEventQueueImpl5flushEv+00000611
[ 61] 0x00002b7e8bba31ed /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwuix.so+00221677
[ 62] 0x00002b7e80d866ea /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwservices.so+02324202
[ 63] 0x00002b7e80d86a24 /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwservices.so+02325028
[ 64] 0x00002b7e80d8257f /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwservices.so+02307455
[ 65] 0x00002b7e80d879b5 /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwservices.so+02329013
[ 66] 0x00002b7e80d87de7 /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwservices.so+02330087
[ 67] 0x00002b7e80d884c0 /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwservices.so+02331840 _Z25svWS_ProcessPendingEventsiib+00000080
[ 68] 0x00002b7e8144c098 /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwmcr.so+00364696
[ 69] 0x00002b7e8144c3bf /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwmcr.so+00365503
[ 70] 0x00002b7e8144728f /stor9000/apps/appsoftware/MATLAB/R2014a/bin/glnxa64/libmwmcr.so+00344719
[ 71] 0x000000308fe079d1                             /lib64/libpthread.so.0+00031185
[ 72] 0x000000308f6e8b6d                                   /lib64/libc.so.6+00953197 clone+00000109


If this problem is reproducible, please submit a Service Request via:
    http://www.mathworks.com/support/contact_us/

A technical support engineer might contact you with further information.

Thank you for your help.** This crash report has been saved to disk as /stor9000/apps/users/NWSUAF/2015050469/matlab_crash_dump.30450-1 **



MATLAB is exiting because of fatal error
0, loglik = -6953.085083
iteration 31, loglik = -6952.859988
iteration 32, loglik = -6952.595921
iteration 33, loglik = -6952.267984
iteration 34, loglik = -6951.841609
iteration 35, loglik = -6951.272535
iteration 36, loglik = -6950.511106
iteration 37, loglik = -6949.528561
iteration 38, loglik = -6948.407954
iteration 39, loglik = -6947.320211
iteration 40, loglik = -6946.327346
iteration 41, loglik = -6945.439897
iteration 42, loglik = -6944.669407
iteration 43, loglik = -6944.009188
iteration 44, loglik = -6943.438726
iteration 45, loglik = -6942.935654
iteration 46, loglik = -6942.482006
iteration 47, loglik = -6942.065124
iteration 48, loglik = -6941.676412
iteration 49, loglik = -6941.309903
iteration 50, loglik = -6940.961231
iteration 51, loglik = -6940.627031
iteration 52, loglik = -6940.304586
iteration 53, loglik = -6939.991632
iteration 54, loglik = -6939.686239
iteration 55, loglik = -6939.386726
iteration 56, loglik = -6939.091606
iteration 57, loglik = -6938.799547
iteration 58, loglik = -6938.509340
iteration 59, loglik = -6938.219872
iteration 60, loglik = -6937.930112
iteration 61, loglik = -6937.639096
iteration 62, loglik = -6937.345913
iteration 63, loglik = -6937.049703
iteration 64, loglik = -6936.749650
iteration 65, loglik = -6936.444979
iteration 66, loglik = -6936.134961
iteration 67, loglik = -6935.818912
iteration 68, loglik = -6935.496201
iteration 69, loglik = -6935.166260
iteration 70, loglik = -6934.828596
iteration 71, loglik = -6934.482806
iteration 72, loglik = -6934.128590
iteration 73, loglik = -6933.765777
iteration 74, loglik = -6933.394341
iteration 75, loglik = -6933.014425
iteration 76, loglik = -6932.626353
iteration 77, loglik = -6932.230650
iteration 78, loglik = -6931.828045
iteration 79, loglik = -6931.419472
iteration 80, loglik = -6931.006056
iteration 81, loglik = -6930.589091
iteration 82, loglik = -6930.170002
iteration 83, loglik = -6929.750305
iteration 84, loglik = -6929.331552
iteration 85, loglik = -6928.915286
iteration 86, loglik = -6928.502985
iteration 87, loglik = -6928.096022
iteration 88, loglik = -6927.695634
iteration 89, loglik = -6927.302894
iteration 90, loglik = -6926.918706
iteration 91, loglik = -6926.543795
iteration 92, loglik = -6926.178721
iteration 93, loglik = -6925.823887
iteration 94, loglik = -6925.479551
iteration 95, loglik = -6925.145853
iteration 96, loglik = -6924.822822
iteration 97, loglik = -6924.510404
iteration 98, loglik = -6924.208470
iteration 99, loglik = -6923.916835
iteration 100, loglik = -6923.635272
iteration 101, loglik = -6923.363519
iteration 102, loglik = -6923.101293
iteration 103, loglik = -6922.848296
iteration 104, loglik = -6922.604219
iteration 105, loglik = -6922.368752
iteration 106, loglik = -6922.141586
iteration 107, loglik = -6921.922415
iteration 108, loglik = -6921.710940
iteration 109, loglik = -6921.506870
iteration 110, loglik = -6921.309924
iteration 111, loglik = -6921.119831
iteration 112, loglik = -6920.936332
iteration 113, loglik = -6920.759176
iteration 114, loglik = -6920.588126
iteration 115, loglik = -6920.422955
iteration 116, loglik = -6920.263446
iteration 117, loglik = -6920.109391
iteration 118, loglik = -6919.960595
iteration 119, loglik = -6919.816869
iteration 120, loglik = -6919.678033
iteration 121, loglik = -6919.543918
iteration 122, loglik = -6919.414359
iteration 123, loglik = -6919.289201
iteration 124, loglik = -6919.168295
iteration 125, loglik = -6919.051497
iteration 126, loglik = -6918.938671
iteration 127, loglik = -6918.829685
iteration 128, loglik = -6918.724413
iteration 129, loglik = -6918.622734
iteration 130, loglik = -6918.524530
iteration 131, loglik = -6918.429690
iteration 132, loglik = -6918.338104
iteration 133, loglik = -6918.249667
iteration 134, loglik = -6918.164279
iteration 135, loglik = -6918.081841
iteration 136, loglik = -6918.002258
iteration 137, loglik = -6917.925438
iteration 138, loglik = -6917.851293
iteration 139, loglik = -6917.779736
iteration 140, loglik = -6917.710684

M =

     6

################################
mdump2 file:
                            < M A T L A B (R) >
                  Copyright 1984-2014 The MathWorks, Inc.
                    R2014a (8.3.0.532) 64-bit (glnxa64)
                             February 11, 2014

 
To get started, type one of these: helpwin, helpdesk, or demo.
For product information, visit www.mathworks.com.
 
Creating diag matrix... Done! 0.0310 seconds
Extracting TAD/Bg matrix-masks... Done! 0.8682 seconds
Gaussianing... Done! 1.0284 seconds
Saving... Done! 0.0577 seconds

#################################
mdump3 file:
                            < M A T L A B (R) >
                  Copyright 1984-2014 The MathWorks, Inc.
                    R2014a (8.3.0.532) 64-bit (glnxa64)
                             February 11, 2014

 
To get started, type one of these: helpwin, helpdesk, or demo.
For product information, visit www.mathworks.com.
 
Loading... Done! 1.3507 seconds
Generating Matrixes... Done! 0.1475 seconds
Supersumming... Done! 3.9909 seconds
Saving... Done! 3.9341 seconds

##################################
mdump4 file:
                            < M A T L A B (R) >
                  Copyright 1984-2014 The MathWorks, Inc.
                    R2014a (8.3.0.532) 64-bit (glnxa64)
                             February 11, 2014

 
To get started, type one of these: helpwin, helpdesk, or demo.
For product information, visit www.mathworks.com.
 
Loading files... Done! 2.0718 seconds
Finding TADs... Finished! Printing solution...
1-1561 
Done! 47.7921 seconds
Saving TADs... Done! 0.0893 seconds

###############################
mdump5 file:
                            < M A T L A B (R) >
                  Copyright 1984-2014 The MathWorks, Inc.
                    R2014a (8.3.0.532) 64-bit (glnxa64)
                             February 11, 2014

 
To get started, type one of these: helpwin, helpdesk, or demo.
For product information, visit www.mathworks.com.
 
Loading files... Done! 1.3079 seconds
Constructing hierarchy... Done! 0.0461 seconds

##########################
mdump6 file:
                            < M A T L A B (R) >
                  Copyright 1984-2014 The MathWorks, Inc.
                    R2014a (8.3.0.532) 64-bit (glnxa64)
                             February 11, 2014

 
To get started, type one of these: helpwin, helpdesk, or demo.
For product information, visit www.mathworks.com.
 
Loading... AAABBBCCCAAA
ans =

Index exceeds matrix dimensions.

Error in RebuildMatrix (line 36)
        chrNum = BED{1}{1};

Error in ModelEstimate (line 6)
        [RES_Hrr,~,~] = RebuildMatrix(matPath,bedPath,0,bedPathOut,res,bilinear);
######################
And the mouse example data has the similar error.

**Comment by dhkron** [comment]
I am quite worried about `sh: line 1: 30450 Killed matlab -nodisplay -r "try HMM_calls ./PSYCHIC-master/examples/output/hIMR90.chr20.DI ./PSYCHIC-master/examples/output/hIMR90.chr20.HMM;catch E;fprintf('AAABBBCCCAAA');getReport(E),end;exit" > ./PSYCHIC-master/examples/output/hIMR90.chr20.mdump1 2> ./PSYCHIC-master/examples/output/hIMR90.chr20.mdump1`
It seems like Matlab crashed in the `HMM_Calls` step.. this means the initial domains are wrong and that could explain why `ModelEstimate` failed.

Is you matlab update?

**Comment by MinngLi** [comment]
I am afried my matlab is not update. (R2014a (8.3.0.532) 64-bit (glnxa64) February 11, 2014)

which version did you use?

**Comment by dhkron** [comment]
My Matlab is `8.4.0.150421 (R2014b)`.

I checked-out the code and run the example `python htad-chain examples/himr90.chr20.conf` and it worked, so must be a difference between our systems.

**Comment by MinngLi** [comment]
Thanks for your help.
This problem solved when I used the version of R2015b (8.6.0.267246)
