### ISSUE TITLE
HiC matrices

### ISSUE THREAD

**Issue by ArtemLuzhin** [dhkron/PSYCHIC#6]
Hello! what about unmapable regions (telomere and centromere and repeats) that usually on HiC matrix represents as NaN's. Does it necessary to convert them to zeros? or PSYCHIC have options for masking? How it influence on PSYCHIC results?

With best regards, Artem.

**Comment by dhkron** [comment]
Hey!

PSYCHIC doesn't covert them to zeros, so it is preferable to make them zeros first.
Also, PSYCHIC uses some external libraries to get first TADs, so better make zeros. 
For the last question- generally, large zero regions should have neutral effect on the results. However smaller domains edges usually tend to stick to unmapaple edges.

**Comment by ArtemLuzhin** [comment]
Ok and thanks for fast response)
